apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-claim
      containers:
        - name: writer
          image: wallas25/log-output-writer:1.10
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
        - name: reader
          image: wallas25/log-output-reader:1.11
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
            - name: shared-data
              mountPath: /usr/src/app/shared
